blog_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_pannel/', include("admin_pannel.urls")),
    path('', include("frontend.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

frontend/forms.py
from django import forms
from admin_pannel.models import Mail,contacts



class add_mail(forms.ModelForm):
    address=forms.EmailField(label="",widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 my-4','placeholder':"Your Email Address",'required':'True'}))
   
    class Meta:
        model=Mail
        fields=('__all__')




class contact_form(forms.ModelForm):
    option = {
    "Business Proposal": "Business Proposal",
    "Personal Proposal": "Personal Proposal",
    "Want to Say Hello": "Want to Say Hello",
    }
    first_name=forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    last_name=forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    email=forms.EmailField(required=True, widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    purpose=forms.ChoiceField(required=True, choices=option, widget=forms.Select(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    description=forms.CharField(required=True, widget=forms.Textarea(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    class Meta:
        model=contacts
        fields=('__all__')

templates/admins/about.html
{% extends 'admins/base.html' %}

{% block body_block %} 
    <style>
        .editor-toolbar button {
            margin-right: 5px;
        }
        .editor-area {
            border: 1px solid #ced4da;
            padding: 10px;
            min-height: 200px;
            overflow-y: auto;
        }
        .post_div{
            box-shadow: 10 10 10 10;
            background-color: #fff;
            padding: 30px;
        }

    </style>    <div class="container mt-5  post_div">
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
              <span class="text-uppercase page-subtitle">Pages</span>
              <h3 class="page-title">Edit About Page</h3>
            </div>
          </div>
        
        <form enctype="multipart/form-data"  method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            {{form.media}}
    
            <input type="submit" class="btn btn-primary" value="Update">
            
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% endblock %}

templates/admins/add-category.html
{% extends 'admins/base.html' %}

{% block body_block %} 
    <style>
        .editor-toolbar button {
            margin-right: 5px;
        }
        .editor-area {
            border: 1px solid #ced4da;
            padding: 10px;
            min-height: 200px;
            overflow-y: auto;
        }
        .post_div{
            box-shadow: 10 10 10 10;
            background-color: #fff;
            padding: 30px;
        }

    </style>    <div class="container mt-5  post_div">
        <h2 class="mb-4">Create New Category</h2>
        
        <form enctype="multipart/form-data"  method="POST" >
            {% csrf_token %}
            {{form.as_p}}
          
    
            <input type="submit" class="btn btn-primary" value="Create">
            
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% endblock %}

templates/admins/add-post.html
{% extends 'admins/base.html' %}

{% block body_block %} 
    <style>
        .editor-toolbar button {
            margin-right: 5px;
        }
        .editor-area {
            border: 1px solid #ced4da;
            padding: 10px;
            min-height: 200px;
            overflow-y: auto;
        }
        .post_div{
            box-shadow: 10 10 10 10;
            background-color: #fff;
            padding: 20px;
        }

    </style>    <div class="container mt-5  post_div">
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
              <span class="text-uppercase page-subtitle">Blog</span>
              <h3 class="page-title">Create New Post</h3>
            </div>
          </div>
        
        <form enctype="multipart/form-data"  method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            {{form.media}}
    
            <input type="submit" class="btn btn-primary" value="Create Post">
            
        </form>
    </div>

    <!-- <script>
        function formatText(command, value = null) {
            document.execCommand(command, false, value);
        }

        document.querySelector('form').addEventListener('submit', function() {
            var content = document.getElementById('postContent').innerHTML;
            document.getElementById('postContentTextArea').value = content;
        });
    </script> -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% endblock %}

templates/admins/add-user.html
{% extends 'admins/base.html' %}

{% block body_block %} 

<style>
  .form-container {
      max-width: 800px;
      margin: auto;
      padding: 2rem;
      box-shadow: 0px 0px 30px 10px #ffffff0e;
      border-radius: 20px;
      background-color: #1a191e;
  }
</style>



<div class="container mt-5">
  <div class="form-container">
    <div class="page-header row no-gutters py-4">
      <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">User</span>
        <h3 class="page-title">Add User</h3>
      </div>
    </div>
      <form id="registrationForm" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary">

  </form>
  </div>
</div>

<!-- Bootstrap JS -->

{% endblock %}

templates/admins/base.html
<!doctype html>
{% load static %}

<html class="no-js h-100" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin Pannel - {{ site.site_name }}</title>
  <meta name="description" content="">
  <link rel="shortcut icon" href="{{ site.fav_icon.url }}" type="image/x-icon">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="{% static "admin/styles/shards-dashboards.1.1.0.min.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static "admin/styles/extras.1.1.0.min.css" %}">
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</head>
<body class="h-100" style="background-color: #1a191e;">
<style>
  body, html {
    color: #ffffff !important;
  }

  table {
    border: 1px solid #dddddd !important;
    box-shadow:10px 10px 19px #0e0f10, -10px -10px 19px #1e1e1e;


  }

  h1, h2, h3, h4, h5, a, p {
    color: #ffffff !important;
  }

  .navbar {
    background-color: #1a191e !important;
  }
  .main-navbar .navbar {
    height: 10rem;
}
.main-sidebar .navbar-brand {
  height: 10rem;
}
body > div > div > aside > div.main-navbar > nav{
  border: none!important;
}
  .navbar-brand {
    color: #ffffff !important;
  }

  .nav-link {
    color: #ffffff !important;
    border-bottom: none !important;
  }
  .nav-link {
    color: #ffffff !important;
    background-color: #1a191e!important;
  }
  .nav-link i{
    color: #fff!important;
  }

select{
  color: #ffffff !important;
    background-color: #1a191e!important;
}
  .nav-link:hover {
    background-color: #1a1a1a !important;
  }
  th{
    background-color:  !important;
  }

  .main-sidebar {
    background-color: #1a191e;
    color: #ffffff !important;
  }

  .navbar-search {
    background-color: #ffffff !important;
    color: #000000 !important;
  }

  .main-content {
    background-color: #1a191e !important;
    color: #ffffff !important;
  }

  .alert {
    color: #ffffff !important;
    background-color: #34353c !important;
    border-color: #34353c !important;
  }

  .alert-success {
    background-color: #28a745 !important;
    color: #ffffff !important;
  }

  .close {
    color: #ffffff !important;
  }

  .material-icons {
    color: #ffffff !important;
  }

  .btn-login {
    background-color: #ffffff !important;
    color: #ffffff !important;
    border: none !important;
  }

  .btn-login:hover {
    background-color: #1d1c1c !important;
  }

  .post_div {
    background-color: #1a191e !important;
    box-shadow: 10px 10px 19px #0e0f10, -10px -10px 19px #1e1e1e;
    border-radius: 30px;
    padding: 50px !important;
  }

  table, tr {
    background-color: #1a191e !important;
    color: #ffffff !important;
    border: 1px solid #ffffff0a !important;
 
  }

  input{
    background-color: #1a191e !important;
    color: #ffffff !important;
  }
span, p, a{
    color: #ffffff !important;
  }
  .cke_dialog_body,.cke_dialog_tab,.cke_302_uiElement,.cke_dialog_ui_button,.cke_reset_all{
    background-color: #1a191e!important;
    color: #fff!important;
  }
  /* Custom Dropdown Hover */
  .nav-item.dropdown:hover .dropdown-menu {
    display: block;
    transition: 1s!important;
  }

  .dropdown-menu {
    display: none;
    background-color: #1a191e;
    border: none;
    box-shadow: 10px 10px 19px #0e0f10, -10px -10px 19px #1e1e1e;
    transition: .5s;
  }

  .dropdown-item {
    color: #ffffff !important;
    transition: .5s;
  }

  .dropdown-item:hover {
    background-color: #1d1c1c !important;
    transition: .5s;
  }

  .settings i{
    color: #ffffff!important;
    font-size: 30px;
    position: absolute;
    bottom: 30px;
    left: 20px;
    transition: .5s;
  }
  .settings i:hover{
    transform: scale(1.5);
    transition: .3s;
  }
  .logout i{
    color: #ffffff!important;
    font-size: 30px;
    position: absolute;
    bottom: 100px;
    left: 20px;
    transition: .5s;
  }
  .logout i:hover{
    transform: scale(1.5);
    transition: .5s;
  }
  .visit-site i{
    color: #ffffff!important;
    font-size: 30px;

    transition: .5s;
  }
  .visit-site{
    position: absolute;
    top: 30px;
    right: 30px;
    transition: .5s;
    z-index: 100;
  }
  .visit-site i:hover{
    transform: scale(1.3);
    transition: .5s;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <!-- Main Sidebar -->
    <a href="{% url '' %}" target="_blank" class="visit-site"> <i class="fa-solid fa-eye" alt="Visit Site"></i> </a>
    <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">

      <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
          <a class="navbar-brand w-100 mr-0" href="{% url 'dashboard' %}" style="">
            <div class="d-table m-auto">
              <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 150px;" src="{{site.logo.url}}" alt="Shards Dashboard">
              
            </div>
          </a>
          <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
            <i class="material-icons">&#xE5C4;</i>
          </a>
        </nav>
      </div>

      <div class="nav-wrapper">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'dashboard' %}">
              <i class="material-icons">edit</i>
              <i class="material-icons">vertical_split</i>
              <span>Blog Dashboard</span>
            </a>
          </li>


    
          <li class="nav-item">
            <a class="nav-link " href="{% url 'posts' %}">
              <i class="material-icons">vertical_split</i>
              <span>Blogs</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'add-post' %}">
              <i class="material-icons">add</i>
              <span>Add Blogs</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'all_categories' %}">
              <i class="material-icons">category</i>
              <span>Categories</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'add-category' %}">
              <i class="material-icons">add</i>
              <span>Add Category</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'mails' %}">
              <i class="material-icons">mail</i>
              <span>Subscribers</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'add-user' %}">
              <i class="material-icons">person_add</i>
              <span>Add User</span>
            </a>
          </li>
       
          <li class="nav-item">
            <a class="nav-link " href="{% url 'my-profile' %}">
              <i class="material-icons">person</i>
              <span>My Profile</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'contacts' %}">
              <i class="material-icons">contacts</i>
              <span>Contacts</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'about-page' %}">
              <i class=" fa-solid fa-file"></i>
              <span>About Page</span>
            </a>
          </li>
          
          <a href="{% url 'logout' %}" onclick="return confirm('Are you sure you want to Logout?');" class="logout"> <i class="fa-solid fa-power-off"></i></a>
          <a href="{% url 'settings' %}" class="settings"> <i class="fa-solid fa-gear"></i></a>
        </ul>
      </div>
    </aside>
    <!-- End Main Sidebar -->
    <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
      <div class="navigation">
        <!-- Navigation content goes here -->
      </div>

      {% if form.errors %}
      <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <i class="fa fa-check mx-2"></i>
        {% for field in form %}
        {% if field.errors %}
            {{field.errors}}
        {% endif %} 
        {% endfor %}
      </div>
      {% endif %}

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <i class="fa fa-check mx-2"></i>
          {{message}}
      </div>
      {% endfor %}
      {% endif %}

      {% block body_block %}
      <!-- Main content block -->
      {% endblock %}
    </main>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/N"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

templates/admins/category.html
{% extends 'admins/base.html' %}

{% block body_block %} 

<style>
   

    h1 {
        text-align: left;
        margin-bottom: 20px;
        color: #151516c4;
        margin: 40px 0;

    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
        background-color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        overflow: hidden;
    }

    th, td {
        padding: 12px 15px;
        text-align: left;
    }

    thead {
        background-color: #007bff;
        color: #ffffff;
    }

    tbody tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    tbody tr:hover {
        background-color: #e9ecef;
    }

    th {
        background-color: #000;
        color: white;
        text-transform: uppercase;
        font-weight: bold;
    }

#categoryTable img {
       width: 50px;
        height: 50px;
        object-fit: cover;
        border-radius: 8%;
    }


</style>

<div class="container">
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
          <span class="text-uppercase page-subtitle">Categories</span>
          <h3 class="page-title">All Categories</h3>
        </div>
      </div>
    <table>
        <thead>
            <tr><th>Image</th>
                <th>Category Name</th>
                <th>Number of Posts</th>
                
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="categoryTable">
            {% for category in categories %}
            <tr>
                <td><img src="{{ category.cat_image.url }}" class="img-fluid" alt="{{category.cat_name}}">
                </td>
    
                <td>{{category.cat_name}}</td>
                <td>{{category.numposts}}</td>
                <td><a class="btn btn-primary btn-sm btn-edit" href="{% url 'edit-category' category.id %}"> Edit</a>
                    <a class="btn btn-danger btn-sm btn-delete" onclick="return confirm('Are you sure you want to delete this item?');" href="{% url 'delete-category' category.id %}"> Delete</a></td>
             
    
    
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/admins/dashboard.html
{% extends 'admins/base.html' %}

{% block body_block %} 

<style>
  .card{
    background: #1a191e;
    box-shadow: 10px 10px 19px #0e0f10, -10px -10px 19px #1e1e1e;
  }

  a:hover{
    text-decoration: none;
  }
  i{
    color: #fff!important;
  }
</style>
          <!-- / .main-navbar -->
          <div class="main-content-container container-fluid px-4">
            <!-- Page Header -->
            <div class="page-header row no-gutters py-4">
              <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Dashboard</span>
                <h3 class="page-title">Blog Overview</h3>
              </div>
            </div>
            <!-- End Page Header -->
            
            <!-- Dark Theme Shortcut Boxes -->
            <div class="row mb-4">
              <div class="col-md-4">
                <a href="{% url 'add-post' %}" class="box-link">
                  <div class="card card-small text-center p-3 text-light">
                    <i class="fas fa-plus fa-3x mb-2 "></i>
                    <h5 class="text-light">Add Blog Post</h5>
                  </div>
                </a>
              </div>
              <div class="col-md-4">
                <a href="{% url 'add-category' %}" class="box-link">
                  <div class="card card-small text-center p-3 text-light">
                    <i class="fas fa-plus fa-3x mb-2 "></i>
                    <h5 class="text-light">Add Category</h5>
                  </div>
                </a>
              </div>
              <div class="col-md-4">
                <a href="{% url 'settings' %}" class="box-link">
                  <div class="card card-small text-center p-3 text-light">
                    <i class="fas fa-cog fa-3x mb-2"></i>
                    <h5 class="text-light">Settings</h5>
                  </div>
                </a>
              </div>
            </div>
            <!-- End Dark Theme Shortcut Boxes -->
   
          </div>
  
{% endblock %}

templates/admins/edit-category.html
{% extends 'admins/base.html' %}

{% block body_block %} 
    <style>
        .editor-toolbar button {
            margin-right: 5px;
        }
        .editor-area {
            border: 1px solid #ced4da;
            padding: 10px;
            min-height: 200px;
            overflow-y: auto;
        }
        .post_div{
            box-shadow: 10 10 10 10;
            background-color: #fff;
            padding: 30px;
        }

    </style>    <div class="container mt-5  post_div">
        <h2 class="mb-4">Create New Post</h2>
        
        <form enctype="multipart/form-data"  method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            {{form.media}}
    
            <input type="submit" class="btn btn-primary" value="Update">
            
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% endblock %}

templates/admins/edit-post.html
{% extends 'admins/base.html' %}

{% block body_block %} 
    <style>
        .editor-toolbar button {
            margin-right: 5px;
        }
        .editor-area {
            border: 1px solid #ced4da;
            padding: 10px;
            min-height: 200px;
            overflow-y: auto;
        }
        .post_div{
            box-shadow: 10 10 10 10;
            background-color: #fff;
            padding: 30px;
        }

    </style>    <div class="container mt-5  post_div">
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
              <span class="text-uppercase page-subtitle">Blog</span>
              <h3 class="page-title">Edit Post</h3>
            </div>
          </div>
        
        <form enctype="multipart/form-data"  method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            {{form.media}}
    
            <input type="submit" class="btn btn-primary" value="Update">
            
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% endblock %}

templates/admins/mail.html
{% extends 'admins/base.html' %}

{% block body_block %}
<style>
    .editor-toolbar button {
        margin-right: 5px;
    }
    .editor-area {
        border: 1px solid #ced4da;
        padding: 10px;
        min-height: 200px;
        overflow-y: auto;
    }
    .post_div {
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
    }

    h1 {
        text-align: left;
        margin-bottom: 20px;
        color: #151516c4;
        margin: 40px 0;

    }

    .table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
        background-color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        overflow: hidden;
    }

    .table th, .table td {
        padding: 8px 12px;
        text-align: left;

    }

    .table-hover tbody tr:hover {
        background-color: #e9ecef;
    }

    .search-box {
        margin-bottom: 20px;
        width: 30%;
        float: left;
    }

    .add-email-form {
        width: 65%;
        float: right;
        display: flex;
        align-items: lef;
        justify-content: space-between;
    }

    .add-email-form .form-group {
        margin: 0;
        flex-grow: 1;
    }

    .add-email-form button {
        margin-left: 10px;
    }
    .add_mail_btn{
        height: 36px;
        margin-left: 15px;
        right: 0;
    }
    form{
        float: right;
        align-items: right;
        height: 50px;
        width: 405px;

    }
    #id_address{
        width: 300px;
    }
</style>

<div class="container mt-5">
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
          <span class="text-uppercase page-subtitle">Mail</span>
          <h3 class="page-title">Subscriber List</h3>
        </div>
      </div>
    <div class="search-box">
        <input type="text" id="searchInput" class="form-control" placeholder="Search for emails...">
    </div>

        <form enctype="multipart/form-data" method="POST" class="form-inline">
            {% csrf_token %}
            <div class="input-group mb-3">
                {{ form.as_p }}
           
           
            <button type="submit" class="btn btn-primary mb-2 add_mail_btn">Add Email</button>

</div>
        </form>



    <table class="table table-striped table-hover mt-4">
        <thead class="thead-dark">
            <tr>
                <th>Emails</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="emailTable">
            {% for email in mails %}
            <tr>
                <td>{{ email.address }}</td>
                <td><a class="btn btn-danger btn-sm btn-delete" href="{% url 'delete-mail' email.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    document.getElementById('searchInput').addEventListener('keyup', function() {
        var searchValue = this.value.toLowerCase();
        var tableRows = document.querySelectorAll('#emailTable tr');

        tableRows.forEach(function(row) {
            var email = row.querySelector('td').innerText.toLowerCase();
            if (email.includes(searchValue)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
</script>

{% endblock %}