blog_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_pannel/', include("admin_pannel.urls")),
    path('', include("frontend.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

frontend/urls.py
from django.conf import urls
from django.urls import path
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
      path('', views.index,name=""),
      path('home', views.index,name="home"),
      path('about', views.about,name="about"),
      path('contact', views.contact,name="contact"),
      path('categories', views.category,name="categories"),
      path('category/<slug>', views.single_category,name="category"),
      path('post/<slug>', views.show_single_post,name="post"),
      

 ]
if settings.DEBUG:
      urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from admin_pannel.models import Mail,contacts



class add_mail(forms.ModelForm):
    address=forms.EmailField(label="",widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 my-4','placeholder':"Your Email Address",'required':'True'}))
   
    class Meta:
        model=Mail
        fields=('__all__')




class contact_form(forms.ModelForm):
    option = {
    "Business Proposal": "Business Proposal",
    "Personal Proposal": "Personal Proposal",
    "Want to Say Hello": "Want to Say Hello",
    }
    first_name=forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    last_name=forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    email=forms.EmailField(required=True, widget=forms.TextInput(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    purpose=forms.ChoiceField(required=True, choices=option, widget=forms.Select(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    description=forms.CharField(required=True, widget=forms.Textarea(attrs={'class':'form-control bg-transparent rounded-0 border-bottom shadow-none pb-15 px-0'}))
    class Meta:
        model=contacts
        fields=('__all__')

frontend/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.db import models
from admin_pannel.models import Category,Post,Settings,contacts,about_content
from .forms import add_mail,contact_form
from django.contrib import messages
from django.core.paginator import Paginator


site_data=Settings.objects.get(id=1)
    # products=Product.objects.all()
    # p=Paginator(products,20)
    # p_no=request.GET.get('page')
    # pages=p.get_page(p_no)
    # total_pages=pages.paginator.num_pages
    # return render(request,'admin_p/products.html',{'products':pages,'total_pages':[n+1 for n in range(total_pages) ] })

def index(request):
    objects=Post.objects.order_by('-date')
    p = Paginator(objects,10)
    p_no=request.GET.get('page')
    posts=p.get_page(p_no)
    total_pages=posts.paginator.num_pages


    title=site_data.site_name +" - " + site_data.site_title
    featured_posts=Post.objects.filter(featured=True)
    mail_form=add_mail()
    if request.method=='GET':
        query=request.GET.get('Search')
        if query != None:
            objects=Post.objects.filter(title__icontains=query)
            p = Paginator(objects,10)
            p_no=request.GET.get('page')
            posts=p.get_page(p_no)
            total_pages=posts.paginator.num_pages

    if request.method=='POST':
        mail_form=add_mail(request.POST)
        if mail_form.is_valid():
            mail_form.save()
            messages.success(request,"Subscribe Successfully")
            return redirect("home")
        
    return render(request,'frontend/index.html',{'posts':posts,'title':title,'site_data':site_data,'featured_posts':featured_posts,'mail_form':mail_form,'total_pages':[n+1 for n in range(total_pages)]})

def about(request):
    title="About"+ " - " + site_data.site_name
    content=about_content.objects.get(id=1)
    title=content.title + " - " + site_data.site_name
    
    return render(request,'frontend/about.html',{'title':title,'content':content, 'site_data':site_data})
    
def contact(request):
    title="Contact"+ " - " + site_data.site_name
    form=contact_form()
    if request.method=='POST':
        form=contact_form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Submited Successfully")
            return redirect("contact")
    return render(request,'frontend/contact.html',{'title':title,'form':form, 'site_data':site_data})

def show_single_post(request,slug):
    post=Post.objects.get(slug=slug)
    title=post.title + " - " + site_data.site_name
    return render(request,'frontend/single-post.html',{'post':post, 'title':title,'site_data':site_data})

    

def category(request):
    # categories=Category.objects.all()
    categories = Category.objects.all()
    return render(request,'frontend/category.html',{'categories':categories,'site_data':site_data})

def single_category(request,slug):
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all()
    title=category.cat_name + " - " + site_data.site_name
    
    posts=Post.objects.filter(category=category)


    return render(request,'frontend/single-category.html',{'posts':posts,'title':title,'site_data':site_data,'categories':categories,'category':category})


 

templates/frontend/about.html
{% extends 'frontend/base.html' %}

{% block body_block %} 
        <div class="container py-4 my-5">      
            <div class="row">
                <div class="col-md-9">
                    <h1 class="text-white add-letter-space mb-5">{{content.title}}</h1>
                  {{content.desc|safe}}
                </div>
            </div>
        </div>
        {% endblock %}

templates/frontend/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
    <!-- theme meta -->
    <meta name="theme-name" content="galaxy" />

    <!-- ** Plugins Needed for the Project ** -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static "frontend/plugins/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "frontend/plugins/fontawesome/css/all.css" %}">
    
    <!-- Main Stylesheet -->
    <link href="{% static "frontend/css/style.css" %}" rel="stylesheet">
   
    <!--Favicon-->

    <link rel="icon" href="{{ site_data.fav_icon.url }}" type="image/x-icon">

</head>
<body>
    <!-- START preloader-wrapper -->
    <div class="preloader-wrapper">
        <div class="preloader-inner">
            <div class="spinner-border text-red"></div>
        </div>
    </div>
    <!-- END preloader-wrapper -->
    
    <!-- START main-wrapper -->
    <section class="d-flex">
  
<!-- start of sidenav -->
<aside><div class="sidenav position-sticky d-flex flex-column justify-content-between">
    <a class="navbar-brand" href="{% url 'home' %}" class="logo">
        <img src="{{ site_data.logo.url }}" alt="">
    </a>
    <!-- end of navbar-brand -->

    <div class="navbar navbar-dark my-4 p-0 font-primary">
        <ul class="navbar-nav w-100">
            <li class="nav-item active">
                <a class="nav-link text-white px-0 pt-0" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link text-white px-0" href="{% url 'categories' %}">Category</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link text-white px-0" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link text-white px-0" href="{% url 'contact' %}">Contact</a>
            </li>
      
      
        </ul>
    </div>
 <ul class="list-inline nml-2">  <!-- end of navbar -->
    {% if site_data.twiter_link == "" %}

    {% else %}
    
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.twiter_link}}" class="text-white text-red-onHover pr-2">
                <span class="fab fa-twitter"></span>
            </a>
        </li>
    
    {% endif %}


    {% if site_data.fb_link == "" %}

    {% else %}
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.fb_link}}" class="text-white text-red-onHover p-2">
                <span class="fab fa-facebook-f"></span>
            </a>
        </li>
        {% endif %}


    {% if site_data.insta_link == "" %}

    {% else %}
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.insta_link}}" class="text-white text-red-onHover p-2">
                <span class="fab fa-instagram"></span>
            </a>
        </li>
    {% endif %}


    {% if site_data.linkedin_link == "" %}

    {% else %}
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.linkedin_link}}" class="text-white text-red-onHover p-2">
                <span class="fab fa-linkedin-in"></span>
            </a>
        </li>
    {% endif %}
    </ul>
    <!-- end of social-links -->
</div></aside>
<!-- end of sidenav -->
    <div class="main-content">
        <!-- start of mobile-nav -->
<header class="mobile-nav pt-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-6">
                <a href="{% url 'home' %}">
                    <img src="{{ site_data.logo.url }}" alt="">
                </a>
            </div>
            <div class="col-6 text-right">
                <button class="nav-toggle bg-transparent border text-white">
                    <span class="fas fa-bars"></span>
                </button>
            </div>
        </div>
    </div>
</header>
<div class="nav-toggle-overlay"></div>
<!-- end of mobile-nav -->







{% block body_block %}

{% endblock %}










<!-- start of footer -->
<footer class="bg-dark">
  <p class="text-center">{{site_data.footer_text}}</p>
</footer>
<!-- end of footer -->
    </div>

    </section>
    <!-- END main-wrapper -->

    <!-- All JS Files -->
    <script src="{% static "frontend/plugins/jQuery/jquery.min.js" %}"></script>
    <script src="{% static "frontend/plugins/bootstrap/bootstrap.min.js" %}"></script>

    <!-- Main Script -->
    <script src="{% static "frontend/js/script.js" %}"></script>
</body>
</html>

templates/frontend/category.html
{% extends 'frontend/base.html' %}

{% block body_block %}
<!-- end of mobile-nav -->
 <style>
    .category-item {
    border: 1px solid #e44d1160; /* Red border */
    transition: transform 0.3s;
    border-radius: 20px;
}

.category-item:hover {
    transform: scale(1.05);
}

.category-item img {
    height: 200px;
    object-fit: cover;
    border-radius: 20px;
}

.card-body h3 {
    color: #e6e6e6; /* Red text */
}

.btn-primary {
    background-color: #e44e11; /* Red background */
    border-color: #e44e11; /* Red border */
}

.btn-primary:hover {
    background-color: #bb2d3b;
    border-color: #bb2d3b;
}
 </style>

<div class="container py-4 my-5">
    <div class="row">
        <div class="col-12">
            <div class="bg-dark p-5 mb-5 text-center">
                <h1 class="text-white add-letter-space">Categories</h1>
                <div class="breadcrumb-wrap mt-3">
                    <a href="index.html">Home</a>
                    <span>/</span>
                    <span>Categories</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Example category item -->
         {% for category in categories %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card category-item bg-dark text-white">
                <img class="card-img-top" src="{{category.cat_image.url}}" alt="Art and Photography">
                <div class="card-body text-center">
                    <h3 class="card-title">{{category.cat_name}}</h3>
                    <a href="{% url 'category' category.slug %}" class="btn btn-primary mt-3">Explore</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- Repeat for other categories -->
    
        <!-- Add more categories as needed -->
    </div>
</div>

{% endblock %}

templates/frontend/contact.html
{% extends 'frontend/base.html' %}

{% block body_block %}       

<style>

#id_purpose{
    padding-bottom:0px!important;
}
.msg-box{
    min-height:75vh ;
    align-items: center;
    vertical-align: middle;
    /* box-shadow: 0 0 10px 10px #00000013; */
    display: flex;
    flex-direction: column;
    justify-content: center;
}
.msg-box h4{
    
    font-size: 30px;
    display: block;
}
.msg-box i{
   
    font-size: 30px;
    border-radius: 50px;
    background-color: #c40e29;
    padding: 30px;
    display: block;
}
</style>
       <div class="container py-4 my-5">
            
            <div class="row">

                {% if messages %}
                {% for message in messages %}
                <div class="col-md-5 m-auto msg-box">
                  <i class="fa fa-check mx-2"></i>
                    
                    <h4>{{message}}</h4>
                </div>
                {% endfor %}
                {% else %}
                

                <div class="col-md-10">
                    <div class="contact-form bg-dark">
                        <h1 class="text-white add-letter-space mb-5">Contact Us</h1>
                        <form method="POST" class="needs-validation" novalidate>
                            {% csrf_token %}
                            
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mb-5">
                                        <label for="firstName" class="text-black-300">Your First Name</label>
                                        {{ form.first_name }}
                                        <p class="invalid-feedback">Your first-name is required!</p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mb-5">
                                        <label for="lastName" class="text-black-300">Your Last Name</label>
                                        {{ form.last_name }}
                                        <p class="invalid-feedback">Your last-name is required!</p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mb-5">
                                        <label for="email" class="text-black-300">E-Mail Address</label>
                                        {{ form.email }}
                                        <p class="invalid-feedback">Your email is required!</p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mb-5">
                                        <label class="text-black-300">What Is This About?</label>
                                        {{ form.purpose }}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group mb-5">
                                        <label for="message" class="text-black-300">Your message</label>
                                        {{ form.description }}
                                        <p class="invalid-feedback">Message is required!</p>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-sm btn-primary">Send Now <img src="images/arrow-right.png" alt=""></button>
                                </div>
                            </div>
                            
                        </form>
                    </div>
                </div>{% endif %}
            </div>



        </div>

        {% endblock %}

templates/frontend/index.html
{% extends 'frontend/base.html' %}

{% block body_block %} 


        <div class="container pt-4 mt-5">
            <div class="row justify-content-between">
                <div class="col-lg-7">


                    {% for post in posts %}

                    <div class="card post-item bg-transparent border-0 mb-5 ">
                        <a href="{% url 'post' post.slug %}">
                            <img class="card-img-top rounded-0" src="media/{{ post.image }}" alt="{{post.title}}">
                        </a>
                        <div class="card-body px-0">
                            <h2 class="card-title">
                                <a class="text-white opacity-75-onHover" href="{% url 'post' post.slug %}">{{post.title}}</a>
                            </h2>
                            <ul class="post-meta mt-3">
                                <li class="d-inline-block mr-3">
                                    <span class="fas fa-clock text-primary"></span>
                                    <a class="ml-1" href="#">{{post.date}}</a>
                                </li>
                                <li class="d-inline-block">
                                    <span class="fas fa-list-alt text-primary"></span>
                                    <a class="ml-1" href="#">{{post.category}}</a>
                                </li>
                            </ul>
                            <p class="card-text my-4">{{post.desc|safe|striptags|truncatewords:50}}......</p>
                            <a href="{% url 'post' post.slug %}" class="btn btn-primary read-more">Read More <img src="images/arrow-right.png" alt=""></a>
                        </div>
                    </div>
                    <!-- end of post-item -->
                     {% empty %}

                     <div class="widget bg-dark p-4 text-center mx-auto">
                        <br>
                        <h2>No Post Found</h2>
                        <br>
                   </div>

                    {% endfor %} <!-- end of post-item -->
                    <!-- pagination -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-left">
                        {% if posts.has_previous %}
                          <li class="page-item ">
                            <a class="page-link" href="?page={{posts.previous_page_number}}" tabindex="-1" >Previous</a>
                          </li>
                          {% else %}
                          <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true" >Previous</a>
                          </li>
                          
                          {% endif %}
                          {%for n in total_pages%}


                          {% if products.number == n %}
                         
                              <li class="page-item active"><a class="page-link" href="?page={{n}}">{{n}}</a></li>
                        
                      {% else %}
                      <li class="page-item "><a class="page-link" href="?page={{n}}">{{n}}</a></li>
                      {% endif %}
                      {% endfor %}
                          {% if posts.has_next %}
                          <li class="page-item ">
                            <a class="page-link" href="?page={{posts.next_page_number}}"  >Next</a>
                          </li>
                          {% else %}
                          <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true" >Next</a>
                          </li>
                          
                          {% endif %}
                        </ul>
                      </nav>
                      <!-- pagination -->
                   
                </div>
                <div class="col-lg-4 col-md-5">
                    <div class="widget bg-dark p-4 text-center">
                        
                        <form class="search-form" method="GET">
                            <div class="input-group">
                                <input type="search" required class="form-control bg-transparent shadow-none rounded-0" name="Search" placeholder="Search here">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <span class="fas fa-search"></span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>







                    <div class="widget text-center">
                        <img class="author-thumb-sm rounded-circle d-block mx-auto" src="images/author-sm.png" alt="">
                        <h2 class="widget-title text-white d-inline-block mt-4">About Us</h2>
                        <p class="mt-4">Welcome to Read the Anime! We are passionate about all things anime and dedicated to bringing you engaging blog posts that explore the latest trends, reviews, and insights from the anime world. Join us on our journey as we dive deep into the stories, characters, and artistry that make anime so captivating.</p>
                        <ul class="list-inline mt-3">
                            {% if site_data.twiter_link == "" %}

    {% else %}
    
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.twiter_link}}" class="text-white text-red-onHover pr-2">
                <span class="fab fa-twitter"></span>
            </a>
        </li>
    
    {% endif %}


    {% if site_data.fb_link == "" %}

    {% else %}
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.fb_link}}" class="text-white text-red-onHover p-2">
                <span class="fab fa-facebook-f"></span>
            </a>
        </li>
        {% endif %}


    {% if site_data.insta_link == "" %}

    {% else %}
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.insta_link}}" class="text-white text-red-onHover p-2">
                <span class="fab fa-instagram"></span>
            </a>
        </li>
    {% endif %}


    {% if site_data.linkedin_link == "" %}

    {% else %}
        <li class="list-inline-item">
            <a target="_blank" href="{{site_data.linkedin_link}}" class="text-white text-red-onHover p-2">
                <span class="fab fa-linkedin-in"></span>
            </a>
        </li>
    {% endif %}
                        </ul>
                    </div>
                    <!-- end of author-widget -->
                    {% if messages %}

                    {% for message in messages %}
                
                    <div class="widget bg-dark p-4 text-center">
                        <h2 class="widget-title text-white d-inline-block mt-4">Thank You For Subscribing Our Newslatter</h2>
            
                        
                    </div>
                
                    {% endfor %}
                    {% else %}
        
                    <div class="widget bg-dark p-4 text-center">
                        <h2 class="widget-title text-white d-inline-block mt-4">Subscribe Now</h2>
                        <p class="mt-4">Subscribe for exclusive anime updates and insights. Join us on Read the Anime for the latest news and reviews!</p>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ mail_form.as_p }}
                                <button type="submit"  class="btn btn-primary">Subscribe Now <img src="images/arrow-right.png"  alt=""></button>
                            </div>
                        </form>
                    </div>
                    {% endif %}
                    <!-- end of subscription-widget -->

                    <div class="widget">
                        <div class="mb-5 text-center">
                            <h2 class="widget-title text-white d-inline-block">Featured Posts</h2>
                        </div>
                     
                        
                        {% for post in featured_posts %}

                        <div class="card post-item bg-transparent border-0 mb-5">
                            <a href="{% url 'post' post.slug %}">
                                <img class="card-img-top rounded-0" src="{{ post.image.url }}" alt="{{post.title}}">
                            </a>
                            <div class="card-body px-0">
                                <h2 class="card-title">
                                    <a class="text-white opacity-75-onHover" href="{% url 'post' post.slug %}">{{post.title}}</a>
                                </h2>
                                <ul class="post-meta mt-3 mb-4">
                                    <li class="d-inline-block mr-3">
                                        <span class="fas fa-clock text-primary"></span>
                                        <a class="ml-1" href="#">{{post.date}}</a>
                                    </li>
                                    <li class="d-inline-block">
                                        <span class="fas fa-list-alt text-primary"></span>
                                        <a class="ml-1" href="#">{{post.category}}</a>
                                    </li>
                                </ul>
                                <a href="{% url 'post' post.slug %}" class="btn btn-primary read-more">Read More <img src="images/arrow-right.png" alt=""></a>
                            </div>
                        </div>

                        {% endfor %}


                        <!-- end of widget-post-item -->
                    </div>
                    <!-- end of post-items widget -->
                </div>
            </div>
        </div>
        
        {% endblock %}

templates/frontend/single-category.html
{% extends 'frontend/base.html' %}

{% block body_block %}       
<!-- end of mobile-nav -->
 <style>
    .card-img-top{
        height: 35vh;
        width: 100%;
        object-fit: cover;
    }


    .widget{
        WIDTH: 100%;
    }
 </style>

        <div class="container py-4 my-5">

            
            <div class="row">
                <div class="col-12">
                    <div class="bg-dark p-5 mb-5">
                        <div class="row no-gutters">
                            <div class="col-xl-6 border-right border-lg-0 pr-0 pr-xl-5">
                                <h1 class="text-white add-letter-space">{{category.cat_name}}</h1>
                                <div class="breadcrumb-wrap mt-3">
                                    <a href="{% url 'home' %}">Home</a>
                                    <span>/</span>
                                    <span>Category</span>
                                </div>
                            </div>
                            <div class="col-xl-6 pl-0 pl-xl-5 mt-4 mt-xl-0">
                                <div class="categores-links text-capitalize">
                                    <h3 class="text-white add-letter-space mb-3">More Categores:</h3>
                                    {% for category in categories %}
                                    <a class="border" href="{% url 'category' category.slug %}">{{category.cat_name}}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row justify-content-between">
   {% if posts %}
        {% for post in posts %}

        <div class="col-lg-6 card post-item bg-transparent border-0 mb-5">
            <a href="{% url 'post' post.slug %}">
                <img class="card-img-top rounded-0" src="{{post.image.url}}" alt="">
            </a>
            <div class="card-body px-0">
                <h2 class="card-title">
                    <a class="text-white opacity-75-onHover" href="{% url 'post' post.slug %}">{{post.title}}</a>
                </h2>
                <ul class="post-meta mt-3">
                    <li class="d-inline-block mr-3">
                        <span class="fas fa-clock text-primary"></span>
                        <a class="ml-1" href="#">{{post.date}}</a>
                    </li>
                    <li class="d-inline-block">
                        <span class="fas fa-list-alt text-primary"></span>
                        <a class="ml-1" href="#">{{post.category}}</a>
                    </li>
                </ul>
                <p class="card-text my-4">{{post.desc|safe|striptags|truncatewords:20}}......</p>
                <a href="{% url 'post' post.slug %}" class="btn btn-primary">Read More <img src="images/arrow-right.png" alt=""></a>
            </div>
        </div>
        {% endfor %}

        {% else %}
        <div class="widget bg-dark p-4 text-center mx-auto">
            <br>
            <h2>No Post Found</h2>
            <br>
       </div>

        {% endif %}
        <!-- end of post-item -->
        

</div>

        
{% endblock %}